/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Resep;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import javax.imageio.ImageIO;

/**
 *
 * @author LENOVO
 */
public class halamanResep extends javax.swing.JFrame {
    private Resep resep;
    
    // Variables declaration
    private JPanel mainPanel;
    private JPanel leftPanel;
    private JPanel rightPanel;
    private JButton backButton;
    private JLabel titleLabel;
    private JPanel imagePanel;
    private JTextArea deskripsiArea;
    private JTextArea bahanArea;
    private JTextArea alatArea;
    private JTextArea langkahArea;
    
    /**
     * Creates new form halamanResep
     */
    public halamanResep(Resep resep) {
        this.resep = resep;
        initComponents();
        customizeComponents();
        loadResepData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // Set up main window
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Resep");
        setSize(1080, 720);
        setLocationRelativeTo(null);
        setResizable(false);
        
        // Main panel with BorderLayout
        mainPanel = new JPanel(new BorderLayout());
        
        // Create split panels
        leftPanel = new JPanel();
        rightPanel = new JPanel();
        
        // Set up left panel
        leftPanel.setLayout(new BoxLayout(leftPanel, BoxLayout.Y_AXIS));
        leftPanel.setBackground(new Color(17, 41, 107)); // #11296b
        leftPanel.setPreferredSize(new Dimension(540, 720));
        
        // Back button
        backButton = new JButton("Kembali");
        backButton.setBackground(new Color(253, 197, 0));
        backButton.setForeground(new Color(17, 41, 107));
        backButton.setFont(new Font("Segoe UI", Font.BOLD, 14));
        backButton.setBorderPainted(false);
        backButton.setFocusPainted(false);
        backButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        backButton.addActionListener(e -> dispose());
        
        JPanel backButtonPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 20));
        backButtonPanel.setOpaque(false);
        backButtonPanel.add(backButton);
        leftPanel.add(backButtonPanel);
        
        // Title
        titleLabel = new JLabel();
        titleLabel.setFont(new Font("Segoe UI", Font.BOLD, 24));
        titleLabel.setForeground(Color.WHITE);
        JPanel titlePanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 10));
        titlePanel.setOpaque(false);
        titlePanel.add(titleLabel);
        leftPanel.add(titlePanel);
        
        // Image panel
        imagePanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if (resep.getFoto() != null && !resep.getFoto().isEmpty()) {
                    try {
                        File imageFile = new File(resep.getFoto());
                        if (imageFile.exists()) {
                            Image img = ImageIO.read(imageFile);
                            // Scale image to fit panel width while maintaining aspect ratio
                            double ratio = (double) img.getWidth(this) / img.getHeight(this);
                            int newWidth = 500; // Fixed width
                            int newHeight = (int) (newWidth / ratio);
                            g.drawImage(img, 20, 0, newWidth, newHeight, this);
                            return;
                        }
                    } catch (Exception e) {
                        System.err.println("Error loading image: " + e.getMessage());
                    }
                }
                // Default background if no image
                g.setColor(Color.LIGHT_GRAY);
                g.fillRect(20, 0, 500, 300);
            }
            
            @Override
            public Dimension getPreferredSize() {
                return new Dimension(540, 300);
            }
        };
        imagePanel.setOpaque(false);
        leftPanel.add(imagePanel);
        
        // Deskripsi
        JLabel deskripsiLabel = new JLabel("Deskripsi");
        deskripsiLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        deskripsiLabel.setForeground(Color.WHITE);
        JPanel deskripsiLabelPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 10));
        deskripsiLabelPanel.setOpaque(false);
        deskripsiLabelPanel.add(deskripsiLabel);
        leftPanel.add(deskripsiLabelPanel);
        
        deskripsiArea = createStyledTextArea();
        JScrollPane deskripsiScroll = createStyledScrollPane(deskripsiArea);
        deskripsiScroll.setPreferredSize(new Dimension(500, 80));
        JPanel deskripsiPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 0));
        deskripsiPanel.setOpaque(false);
        deskripsiPanel.add(deskripsiScroll);
        leftPanel.add(deskripsiPanel);
        
        // Bahan dan Alat
        JLabel bahanAlatLabel = new JLabel("Alat dan Bahan");
        bahanAlatLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        bahanAlatLabel.setForeground(Color.WHITE);
        JPanel bahanAlatLabelPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 10));
        bahanAlatLabelPanel.setOpaque(false);
        bahanAlatLabelPanel.add(bahanAlatLabel);
        leftPanel.add(bahanAlatLabelPanel);
        
        // Combined bahan and alat
        JPanel bahanAlatPanel = new JPanel(new GridLayout(2, 1, 0, 10));
        bahanAlatPanel.setOpaque(false);
        
        bahanArea = createStyledTextArea();
        alatArea = createStyledTextArea();
        
        JScrollPane bahanScroll = createStyledScrollPane(bahanArea);
        JScrollPane alatScroll = createStyledScrollPane(alatArea);
        
        bahanAlatPanel.add(bahanScroll);
        bahanAlatPanel.add(alatScroll);
        
        JPanel bahanAlatWrapperPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 0));
        bahanAlatWrapperPanel.setOpaque(false);
        bahanAlatWrapperPanel.add(bahanAlatPanel);
        leftPanel.add(bahanAlatWrapperPanel);
        
        // Set up right panel
        rightPanel.setLayout(new BoxLayout(rightPanel, BoxLayout.Y_AXIS));
        rightPanel.setBackground(new Color(237, 237, 237)); // #ededed
        
        // Langkah-langkah section
        JLabel langkahLabel = new JLabel("Langkah-langkah");
        langkahLabel.setFont(new Font("Segoe UI", Font.BOLD, 18));
        langkahLabel.setForeground(new Color(17, 41, 107));
        JPanel langkahLabelPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 20));
        langkahLabelPanel.setOpaque(false);
        langkahLabelPanel.add(langkahLabel);
        rightPanel.add(langkahLabelPanel);
        
        langkahArea = createStyledTextArea();
        JScrollPane langkahScroll = createStyledScrollPane(langkahArea);
        langkahScroll.setPreferredSize(new Dimension(500, 600));
        JPanel langkahPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 20, 0));
        langkahPanel.setOpaque(false);
        langkahPanel.add(langkahScroll);
        rightPanel.add(langkahPanel);
        
        // Add panels to main panel
        mainPanel.add(leftPanel, BorderLayout.WEST);
        mainPanel.add(rightPanel, BorderLayout.CENTER);
        
        setContentPane(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private JTextArea createStyledTextArea() {
        JTextArea textArea = new JTextArea();
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        textArea.setBackground(Color.WHITE);
        textArea.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        return textArea;
    }
    
    private JScrollPane createStyledScrollPane(JTextArea textArea) {
        JScrollPane scrollPane = new JScrollPane(textArea);
        scrollPane.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        scrollPane.setPreferredSize(new Dimension(500, 100));
        return scrollPane;
    }
    
    private void customizeComponents() {
        // Additional customization if needed
    }
    
    private void loadResepData() {
        titleLabel.setText(resep.getJudul());
        // Assuming you'll add a description field to your Resep class
        // deskripsiArea.setText(resep.getDeskripsi());
        deskripsiArea.setText("Deskripsi resep " + resep.getJudul());
        bahanArea.setText(resep.getBahan());
        alatArea.setText(resep.getAlat());
        langkahArea.setText(resep.getLangkah());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halamanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halamanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halamanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halamanResep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halamanResep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
